# Generated by Django 6.0 on 2025-12-05 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True)),
                ('exams', models.CharField(blank=True, max_length=200)),
                ('min_score', models.CharField(blank=True, max_length=100)),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('scholarships', models.TextField(blank=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='api.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('exchange', 'Обмен'), ('double_degree', 'Двойной диплом'), ('internship', 'Стажировка')], max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_programs', to='api.university')),
            ],
        ),
    ]
