# Generated by Django 6.0 on 2025-12-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admissioninfo_internationalcooperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioninfo',
            name='program',
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='exams',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='min_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='api.university'),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
